
training:
  batch_size: 8
  accum: 1
  n_iters: 100000
  snapshot_freq: 1000
  eval_freq: 1000
  log_freq: 50
  weight: standard
  snapshot_sampling: True
  ema: 0.9999

data:
  train: wikitext2
  valid: lambada
  cache_dir: _data

model:
  name: small
  type: ddit
  hidden_size: 256
  cond_dim: 128
  length: 32
  n_blocks: 4
  n_heads: 4
  scale_by_sigma: True
  dropout: 0.1

graph:
  type: absorb
  file: data
  report_all: False

noise:
  type: loglinear
  sigma_min: 1e-4
  sigma_max: 20

sampling:
  predictor: euler
  steps: 128
  noise_removal: True

eval:
  batch_size: 16
  perplexity: True
  perplexity_batch_size: 4

optim:
  weight_decay: 0
  optimizer: AdamW
  lr: 0.0001
  beta1: 0.9
  beta2: 0.999
  eps: 0.00000001
  warmup: 2500
  grad_clip: 1.
