defaults:
  - _self_
  - model: small
  - override hydra/launcher: submitit_slurm

ngpus: 1
tokens: 384

training:
  batch_size: 1
  accum: 1
  n_iters: 1300001
  snapshot_freq: 1000
  log_freq: 50
  eval_freq: 500
  weight: standard
  snapshot_sampling: True
  ema: 0.9999
  output_dir: train_baby_names

data:
  train: baby_names_train
  valid: baby_names_test
  cache_dir: data
  oxen:
    remote_repo: ox/Score-Entropy-Discrete-Diffusion-ctx-64

graph:
  type: absorb
  file: data
  report_all: False

noise:
  type: loglinear
  sigma_min: 1e-4
  sigma_max: 20

sampling:
  predictor: euler
  steps: 128
  noise_removal: True

eval:
  batch_size: 512
  perplexity: True
  perplexity_batch_size: 1

optim:
  weight_decay: 0
  optimizer: AdamW
  lr: 0.0003
  beta1: 0.9
  beta2: 0.999
  eps: 0.00000001
  warmup: 2500
  grad_clip: 1.

model:
  name: small
  type: ddit
  hidden_size: 768
  cond_dim: 128
  length: 64
  n_blocks: 8
  n_heads: 8
  scale_by_sigma: True
  dropout: 0.1

hydra:
  run:
    dir: exp_local/${data.train}/${now:%Y.%m.%d}/${now:%H%M%S}
  sweep:
    dir: exp/${data.train}/${now:%Y.%m.%d}/${now:%H%M%S}
    subdir: ${hydra.job.num}
  launcher:
    max_num_timeout: 100000
    # timeout_min: 10079
    partition: g40x
    account: stanford
    mem_gb: 96
    cpus_per_task: 40
    gpus_per_node: ${ngpus}
    constraint: null
